public with sharing class CTRecentChangesController {
    @AuraEnabled
    public static List<Person__c> getRecentPersonHealthChanges (){
        return null;
    }
    @AuraEnabled
    public static List<Location__c> getRecentLocationHealthChanges (){
        return null;
    }
    @AuraEnabled
    public static List<People_Tracing__c> searchPeople (String qryTerm){
        return null;
    }
    @AuraEnabled
    public static List<Location_Tracing__c> searchLocation (String qryTerm){
        return null;
    }
}
